CREATE TABLE [EDNAMaterial].[Material_Details] (
    [EntityID]                                        VARCHAR (100)   NOT NULL,
    [Material_Code]                                   VARCHAR (40)    NOT NULL,
    [Family_Item_ID]                                  VARCHAR (6)     NOT NULL,
    [Language_Key]                                    NVARCHAR (40)   NOT NULL,
    [Material_Desc_Uppercase]                         NVARCHAR (4000) NULL,
    [Material_Type]                                   VARCHAR (4)     NULL,
    [Industry_Sector]                                 CHAR (1)        NULL,
    [Material_Group]                                  VARCHAR (9)     NULL,
    [Old_Material_Number]                             VARCHAR (40)    NULL,
    [Base_Unit]                                       VARCHAR (3)     NULL,
    [Purchasing_Value_Key]                            VARCHAR (4)     NULL,
    [Gross_Weight]                                    FLOAT (53)      NULL,
    [Net_Weight]                                      FLOAT (53)      NULL,
    [Weight_Unit]                                     VARCHAR (3)     NULL,
    [Volume]                                          FLOAT (53)      NULL,
    [Volume_Unit]                                     VARCHAR (3)     NULL,
    [Container_Requirements]                          VARCHAR (2)     NULL,
    [Storage_Conditions]                              VARCHAR (2)     NULL,
    [Temperature_Conditions_Indicator]                VARCHAR (2)     NULL,
    [Low_Level_Code]                                  VARCHAR (3)     NULL,
    [Transportation_Group]                            VARCHAR (10)    NULL,
    [Division]                                        VARCHAR (2)     NULL,
    [EAN_UPC]                                         VARCHAR (18)    NULL,
    [International_Article_Number_EAN_Category]       VARCHAR (2)     NULL,
    [Length]                                          FLOAT (53)      NULL,
    [Width]                                           FLOAT (53)      NULL,
    [Height]                                          FLOAT (53)      NULL,
    [Unit_of_Dimension_for_Length_Width_Height]       VARCHAR (3)     NULL,
    [Cross_Plant_Material_Status]                     VARCHAR (2)     NULL,
    [Cross_Plant_Material_Status_Validity_Start_Date] DATETIME2 (7)   NULL,
    [Manufacturer_Part_Number]                        VARCHAR (40)    NULL,
    [Manufacturer_number]                             VARCHAR (10)    NULL,
    [Manufacturer_Part_Profile]                       VARCHAR (4)     NULL,
    [Units_of_Measure_Usage]                          CHAR (1)        NULL,
    [Base_Unit_of_Measure]                            VARCHAR (3)     NULL,
    [Complete_Material_Maintenance_Status]            VARCHAR (15)    NULL,
    [Maintenance_status]                              VARCHAR (15)    NULL,
    [Level1_Deletion_Delete_Flag]                     CHAR (1)        NULL,
    [Record_Active_Start_Time]                        DATETIME        NULL,
    [Record_Active_End_Time]                          DATETIME        NULL,
    [Src_Loaded_Time]                                 DATETIME        NULL,
    [Src_Loaded_By]                                   VARCHAR (200)   NULL,
    [Src_Updated_Time]                                DATETIME        NULL,
    [Src_Updated_By]                                  VARCHAR (200)   NULL,
    [Active_Status]                                   BIT             NULL,
    [LastUpdated]                                     DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([EntityID] ASC)
);

