CREATE TABLE [EDNAWorkforce].[Worker_test] (
    [EntityID]                        INT            NULL,
    [LastUpdated]                     DATETIME2 (7)  NULL,
    [Employee_ID]                     INT            NULL,
    [First_Name]                      NVARCHAR (256) NULL,
    [Middle_Name]                     NVARCHAR (256) NULL,
    [Last_Name]                       NVARCHAR (256) NULL,
    [Preferred_First_Name]            NVARCHAR (256) NULL,
    [Preferred_Middle_Name]           NVARCHAR (256) NULL,
    [Preferred_Last_Name]             NVARCHAR (256) NULL,
    [User_name]                       NVARCHAR (256) NULL,
    [Gender]                          NVARCHAR (256) NULL,
    [Date_of_birth]                   DATE           NULL,
    [Phone_Number]                    NVARCHAR (256) NULL,
    [Home_Phone_Number]               NVARCHAR (256) NULL,
    [Emergency_contact_name]          NVARCHAR (256) NULL,
    [Emergency_contact_number_home]   NVARCHAR (256) NULL,
    [Emergency_contact_number_work]   NVARCHAR (256) NULL,
    [Office_Address]                  NVARCHAR (256) NULL,
    [Email_Work]                      NVARCHAR (256) NULL,
    [Primary_Work_Email]              NVARCHAR (256) NULL,
    [Location]                        NVARCHAR (256) NULL,
    [Location_Code]                   NVARCHAR (256) NULL,
    [Location_address_City]           NVARCHAR (256) NULL,
    [Location_address_State]          NVARCHAR (256) NULL,
    [Location_Address_Country]        NVARCHAR (256) NULL,
    [Postal_Code]                     NVARCHAR (256) NULL,
    [Time_zone]                       NVARCHAR (256) NULL,
    [Location_Reference_ID]           NVARCHAR (256) NULL,
    [Drop_Code]                       NVARCHAR (256) NULL,
    [Affiliate]                       NVARCHAR (256) NULL,
    [Hub]                             NVARCHAR (256) NULL,
    [Position_ID]                     INT            NULL,
    [Position_Title]                  NVARCHAR (256) NULL,
    [Previous_System_ID]              NVARCHAR (256) NULL,
    [Domain]                          NVARCHAR (256) NULL,
    [Is_Manager]                      NVARCHAR (256) NULL,
    [Hire_Date]                       DATETIME2 (7)  NULL,
    [Original_Hire_Date]              DATETIME2 (7)  NULL,
    [Job_Title]                       NVARCHAR (256) NULL,
    [Job_Classification_ID]           NVARCHAR (256) NULL,
    [Job_Code]                        NVARCHAR (256) NULL,
    [Job_Family]                      NVARCHAR (256) NULL,
    [Job_Family_Group]                NVARCHAR (256) NULL,
    [Active_Status]                   NVARCHAR (256) NULL,
    [Contract_End_Date]               DATETIME2 (7)  NULL,
    [Status]                          NVARCHAR (256) NULL,
    [Supplier]                        NVARCHAR (256) NULL,
    [Secondary_Vendor]                NVARCHAR (256) NULL,
    [Manager_Employee_ID]             INT            NULL,
    [Supervisor]                      NVARCHAR (256) NULL,
    [Supervisory_Org_Name]            NVARCHAR (256) NULL,
    [Supervisory_Organization_ID]     NVARCHAR (256) NULL,
    [supervisor_location_hierarchies] NVARCHAR (256) NULL,
    [Time_Type]                       NVARCHAR (256) NULL,
    [Worker_Type]                     NVARCHAR (256) NULL,
    [Cost_Center_ID]                  NVARCHAR (256) NULL,
    [Cost_Centre]                     NVARCHAR (256) NULL,
    [Cost_Center_Name]                NVARCHAR (256) NULL,
    [Worker_Sub_Type]                 NVARCHAR (256) NULL,
    [Contingent_Worker_Supplier]      NVARCHAR (256) NULL,
    [Currently_Active]                NVARCHAR (256) NULL,
    [Retiree]                         NVARCHAR (256) NULL,
    [RSA_Unique_Personel_ID]          NVARCHAR (256) NULL,
    [RSA_Email_Work]                  NVARCHAR (256) NULL,
    [Active_Ind]                      NVARCHAR (256) NULL,
    [Effective_Startdate]             DATETIME2 (7)  NULL,
    [Effective_Enddate]               DATETIME2 (7)  NULL,
    [Is_Updated]                      VARCHAR (256)  NULL
);

