
CREATE VIEW [EDNAMaterial].[vw_EntityMaterialDetails]
AS SELECT  [EntityID]
		,[Material_Code]
		,[Language_Key]
		,[Family_Item_ID]
		,[Material_Desc_Uppercase]
		,[Material_Type]
		,[Industry_Sector]
		,[Material_Group]
		,[Old_Material_Number]
		,[Base_Unit]
		,[Purchasing_Value_Key]
		,[Gross_Weight]
		,[Net_Weight]
		,[Weight_Unit]
		,[Volume]
		,[Volume_Unit]
		,[Container_Requirements]
		,[Storage_Conditions]
		,[Temperature_Conditions_Indicator]
		,[Low_Level_Code]
		,[Transportation_Group]
		,[Division]
		,[EAN_UPC]
		,[International_Article_Number_EAN_Category]
		,[Length]
		,[Width]
		,[Height]
		,[Unit_of_Dimension_for_Length_Width_Height]
		,[Cross_Plant_Material_Status]
		,[Cross_Plant_Material_Status_Validity_Start_Date]
		,[Manufacturer_Part_Number]
		,[Manufacturer_number]
		,[Manufacturer_Part_Profile]
		,[Units_of_Measure_Usage]
		,[Base_Unit_of_Measure]
		,[Complete_Material_Maintenance_Status]
		,[Maintenance_status]
		,[Level1_Deletion_Delete_Flag]
		,[Record_Active_Start_Time]
		,[Record_Active_End_Time]
		,[Src_Loaded_Time]
		,[Src_Loaded_By]
		,[Src_Updated_Time]
		,[Src_Updated_By]
		,[Active_Status]
		,[LastUpdated]
  FROM [EDNAMaterial].[Material_Details]

